### PR TITLE
[WIP] Observable Tree

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR is a work-in-progress experiment to see if it's feasible to build an observable tree structure. 

Feedback is welcome!

### CODE REVIEW

**Comment by srdanrasic** [comment]
This is super interesting @tonyarnold! 💥 

I wonder if ObservableTree could use CollectionOperation instead of TreeOperation and then get all the diffing for free. CollectionOperation has same set of cases as TreeOperation and it is generic over Index type so maybe we could fo `typealias TreeOperation = CollectionOperation<IndexPath>`?

**Comment by srdanrasic** [comment]
Another idea: `ObservableTree` as `ObservableCollection<TreeNode>` where `TreeNode` is a `Collection` with `IndexPath` for `Index`.

**Comment by tonyarnold** [comment]
Interesting ideas - I'll have a poke at it today and see what I can come up with. Thanks for the feedback and encouragement!

**Comment by tonyarnold** [comment]
> Or was your idea that this should replace ObservableCollection?

Oh geez, no. This is going to be pretty unoptimised in places - `ObservableCollection` will still (for now) be a faster, simpler option. I mean, I guess we _could_ potentially use this to back the same ideas as `ObservableCollection`…

**Comment by tonyarnold** [comment]
> `ObservableTree` as `ObservableCollection<TreeNode>` where `TreeNode` is a `Collection` with `IndexPath` for `Index`

I think this might be the winner. I really wanted the various levels of the tree to do their own change tracking/sending, but I'm not sure that's going to work.

**Comment by srdanrasic** [comment]
@tonyarnold I'm thinking what's the best way to port `Observable2DArray` to our new `ObservableCollection` type. 

Currently `Observable2DArray` is backed by an array of `Observable2DArraySection<Metadata, Item>` but that will not work well with `ObservableCollection`.

What seems to be a natural data structure for something like that is actually a tree. I'm playing with your `TreeNode`, but I'm hitting a wall with child -> parent relationship so I'm wondering is that something we really need?

**Comment by tonyarnold** [comment]
No, it’s not necessary to be honest. I need it for my use case, but I believe you could make the rest of tree node work without it.

**Comment by tonyarnold** [comment]
I didn't make time to look at this last night, I'll see what I can do tonight once the kids are asleep - I also realise that `children` should be a Collection or Array of `Self`, not a direct reference to the type.

**Comment by srdanrasic** [comment]
Oh, no worries, that was not my intention. I started playing with it on my own branch. Don’t have much yet though.

**Comment by tonyarnold** [comment]
So the main issue I can see is that it doesn’t appear to be possible to construct a proper index path for the various events, ie.: 

```swift
/// Append `newElement` at the end of the collection.
public func append(_ newElement: UnderlyingTreeNode.Element) {
    descriptiveUpdate { (node) -> [TreeOperation] in
        var parent = node as! UnderlyingTreeNode.Element
        parent.children.append(newElement)
        let insertionIndex = parent.children.index(parent.children.endIndex, offsetBy: -1)
        return [.insert(at: parent.indexPath.appending(insertionIndex))]
    }
}
```

My brain’s not firing on all cylinders, but perhaps there’s some way to make this work without having direct access to the parent’s index path? Do you have any ideas, @srdanrasic?

**Pull request merged**
