### PR TITLE
Add support for NSCollectionView data source bindings

### PR DESCRIPTION
**Pull request by tonyarnold**
This PR aims to add full support for AppKit's NSCollectionView. I am currently using the Flat Data Source variant in one of my own projects, and it is working well. 

This PR will need ~tests and~ review. (There's no macOS test target, and I don't think adding one as part of this PR is a great idea - I'll make a separate PR for that).

### CODE REVIEW

**Comment by srdanrasic** [comment]
This looks cool @tonyarnold! 

Thinking about this... do we actually need `NSCollectionView+FlatDataSource.swift`? Can't we just use the sectioned variant? Flat collections like `Array` or `ObservableArray` conform to `SectionedDataSourceProtocol` as well.

**Comment by tonyarnold** [comment]
That makes sense, however my use case is with a `MutableObservableCollection` - I see that `Collection` doesn't (can't?) conform to `QueryableSectionedDataSourceProtocol` and `SectionedDataSourceChangesetConvertible`.

**Comment by tonyarnold** [comment]
I’m going to try to conform my list types to the section protocols. I’ll let you know how it goes :+1:

**Comment by tonyarnold** [comment]
Yep, that did it - all good, I've revised the PR to remove the flat data source variant, and renamed the sectioned data source to make it simpler.

**Comment by tonyarnold** [comment]
How are you feeling about this PR, @srdanrasic - there's absolutely no rush, but I'd love to get these classes out of my local project and into a released version of Bond.

**Comment by srdanrasic** [comment]
Looks great to me @tonyarnold, thanks for working on it! I'll make a release.

**Pull request merged**
