### PR TITLE
[WIP] Bond 7

### PR DESCRIPTION
**Pull request by srdanrasic**
- [x] Observable collections refactor
- [x] New UITableView binder
- [x] New UICollectionView binder
- [x] New NSTableView binder 
- [x] New NSOutlineView binder
- [x] Changeset signal map/filter/sort
- [ ] Documentation
- [ ] More tests

Observable collections is now just a `Property` of a value type conforming to `ChangesetProtocol`.

### CODE REVIEW

**Comment by srdanrasic** [comment]
@tonyarnold `objectValueFor` data source method seems to be called in between begin/endUpdates after each patch, expecting the underlying collection to be be patched incrementally as operations are reported by calling `insertRows`, `removeRows`, etc.

The only solution I could think of is to have the binder keep local clone of the collection, like the outline view binder does.

This is different than what UIKit does - waits for all batch operations to complete and then queries the data source.

**Comment by tonyarnold** [comment]
@srdanrasic yeah, that definitely works. I'm still feeling a lot of friction around the wrapping of the datasource - I wonder if there is a way that the Binder could still be the datasource, but also have its own optional `dataSource` property that it calls before using its own implementation? That might make things simpler in terms of implementation (the ProtocolProxy handlers are a bit unwieldy in use IMO). 

What would be the best way to implement this? Allow there to be an array of `forwardTo` objects in `ProtocolProxy` and we just ask them in sequence until one is hit that implements the method we're looking for?

**Comment by tonyarnold** [comment]
Thanks, @srdanrasic. 

I ended up creating subclasses of the binders for my custom implementation after posting this question, and that has worked a treat 👍

**Comment by tonyarnold** [comment]
Ok, alongside the work in PR #566, this is all working really nicely for me - thanks for your hard work @srdanrasic!

**Comment by srdanrasic** [comment]
Great to hear that @tonyarnold! I’ll try to write some docs over the weekend and prepare for a release.

**Pull request merged**
