### PR TITLE
[README] Document installation via Accio

### PR DESCRIPTION
**Pull request by Dschee**
This documents support for the new SwiftPM based dependency manager [Accio](https://github.com/JamitLabs/Accio).

Please note that this project is part of Accio's official [integration tests](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo/Shared/AppDependencies) within the [Demo project](https://github.com/JamitLabs/Accio/tree/work/1000-frameworks/Demo).

### CODE REVIEW

**Comment by srdanrasic** [comment]
What is the reason behind `AccioSupport/ReactiveKit`? If there is something in ReactiveKit missing, maybe we can fix it?

**Comment by Dschee** [comment]
@srdanrasic I just tried fixing https://github.com/JamitLabs/Accio/issues/21 and played around a little. I think it's better if you wait with merging this until I figured it out and the integration tests are running properly. I will inform you once that's the case. I will also report any issues I might find in ReactiveKit.

**Comment by Dschee** [comment]
@srdanrasic I found the issue and it lies within Bond, not ReactiveKit, so I reverted to the original repo.

The issue was that you seem to include the subdependencies of Bond via Submodule, which caused linking errors because subdependencies are built separately in Accio. I'm not sure if it is good practice to use submodules, if I recall correctly Carthage added submodule support relatively late and I'm not sure if it's a good idea to do so in a framework. In any case, Accio is currently not compatible with this style, so I applied to "normal" way of including dependencies.

I hope this is fine with you. If you have any other suggestions how this could be tackled, I'm open for improving Accio in that regard. But as I'm not a complete pro in all the details on how Xcode is linking everything, I don't know how else to fix it.

**Comment by srdanrasic** [comment]
Thanks @Dschee! This broke playgrounds and tests, but I was able to fix them. Released as 7.4.2.

**Comment by Dschee** [comment]
Thank you very much @srdanrasic!

**Pull request merged**
