### PR TITLE
[WIP] Update syntax to Swift 4.1.

### PR DESCRIPTION
**Pull request by srdanrasic**
This updates syntax to Swift 4.1 and project to Xcode 9.3.

- [x] Update Differ to Swift 4.1

### CODE REVIEW

**Comment by srdanrasic** [comment]
@tonyarnold I see that you already made some updates to Differ regarding Swift 4.1. Do you plan to release a new version that is Swift 4.1 warning free?

**Comment by tonyarnold** [comment]
Yes, absolutely. It’s pretty much ready, I’m just thinking through how to release it so it doesn’t impact users still on Swift 4.0. I’ll finalise and release an update tomorrow 👍🏻

**Comment by srdanrasic** [comment]
I'm planning to bump minor version number for Bond. That's the usual approach as far as I know. I don't think it justifies the major version number update.

**Comment by tonyarnold** [comment]
Sorry about the delay - you should be able to bump to Differ 1.1.0 for Swift 4.1 compatibility.

**Pull request merged**
